# Generated by Django 6.0.5 on 2026-06-02 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_tier', models.CharField(choices=[('starter', 'Starter Plan (1 Credit)'), ('plus', 'Plus Plan (2 Credits)'), ('basic', 'Basic Plan (12 Credits)'), ('standard', 'Standard Plan (40 Credits)'), ('printing-pro', 'Printing Pro Package (150 Credits)'), ('enterprise', 'Enterprise Plan (700 Credits)')], max_length=30)),
                ('transaction_reference', models.CharField(blank=True, help_text='The unique transaction reference ID from Telebirr, CBE, or Bank transfer.', max_length=100, null=True, unique=True, verbose_name='Transaction Ref / Reference Number')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved & Credited'), ('rejected', 'Rejected/Invalid')], default='pending', max_length=20)),
                ('receipt_image_base64', models.TextField(help_text='Base64 string representing the compressed image verification proof.', verbose_name='Receipt Image String')),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from checking staff members.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Verification',
                'verbose_name_plural': 'Payment Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
