# Generated by Django 6.0.5 on 2026-05-21 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique job identifier. Used in result/download URLs.', primary_key=True, serialize=False)),
                ('approach', models.CharField(choices=[('approach_one', 'Approach 1 (Standard Layout Extraction)'), ('approach_two', 'Approach 2 (Alternative/Variant Extraction)')], default='approach_one', help_text='The layout structure/strategy used to parse and combine the elements.', max_length=50, verbose_name='extraction approach')),
                ('input_filename_one', models.CharField(blank=True, help_text='Original filename of the first component file.', max_length=255, verbose_name='original filename one')),
                ('input_bytes_one', models.BinaryField(help_text='Raw bytes of the first uploaded component. Wiped after processing.', verbose_name='input file one bytes')),
                ('input_filename_two', models.CharField(blank=True, help_text='Original filename of the second component file.', max_length=255, verbose_name='original filename two')),
                ('input_bytes_two', models.BinaryField(help_text='Raw bytes of the second uploaded component. Wiped after processing.', verbose_name='input file two bytes')),
                ('output_bytes', models.BinaryField(blank=True, help_text='Raw JPEG bytes of the compiled landscape output. Wiped after download.', null=True, verbose_name='output file bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, help_text="Populated when status='failed'. Empty otherwise.", verbose_name='error message')),
                ('watermarked', models.BooleanField(default=False, help_text='True if the output has a free-tier watermark.', verbose_name='watermarked')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text="Set when status transitions to 'done' or 'failed'.", null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Owner of this job. Null for anonymous free-tier conversions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversion job',
                'verbose_name_plural': 'conversion jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversionQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Current quota period in YYYY-MM format.', max_length=7, verbose_name='period')),
                ('conversions_used', models.PositiveIntegerField(default=0, verbose_name='conversions used')),
                ('conversions_allowed', models.IntegerField(default=3, help_text='-1 means unlimited.', verbose_name='conversions allowed')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversion quota',
                'verbose_name_plural': 'conversion quotas',
            },
        ),
    ]
