# Generated by Django 6.0.5 on 2026-05-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='residential address'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='date_of_expiry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='date of expiry'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='fin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='fin number'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id number'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nationality'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='serial number'),
        ),
    ]
