# Generated by Django 6.0.5 on 2026-05-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0002_conversionjob_address_conversionjob_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversionjob',
            name='address',
        ),
        migrations.RemoveField(
            model_name='conversionjob',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='conversionjob',
            name='date_of_expiry',
        ),
        migrations.RemoveField(
            model_name='conversionjob',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='conversionjob',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='conversionjob',
            name='name',
        ),
        migrations.RemoveField(
            model_name='conversionjob',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='conversionjob',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='conversionjob',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='conversionjob',
            name='sn',
        ),
    ]
