# Generated by Django 6.0.5 on 2026-06-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0003_remove_conversionjob_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionquota',
            name='conversions_allowed',
            field=models.IntegerField(default=3, help_text='Total lifetime credits granted to the user. Set to -1 for unlimited access.', verbose_name='credits granted'),
        ),
        migrations.AlterField(
            model_name='conversionquota',
            name='conversions_used',
            field=models.PositiveIntegerField(default=0, help_text='Total number of conversions this user has completed over their lifetime.', verbose_name='credits consumed'),
        ),
        migrations.AlterField(
            model_name='conversionquota',
            name='period',
            field=models.CharField(default='LIFETIME', help_text="Legacy field retained for migration stability. Set to 'LIFETIME'.", max_length=7, verbose_name='period label'),
        ),
    ]
